name: laboratory
channels:
  - conda-forge
  - defaults
  - nvidia/label/cuda-12.4.1
dependencies:
  - python=3.11
  - pip
  - cmake>=3.23
  - ffmpeg
  - cuda-toolkit=12.4.1
  - pyyaml
  - matplotlib
  - scipy 
  - numpy
  - pip:
    - pyyaml
    - matplotlib
    - scipy 
    - numpy==1.25
    - torch
    - torchvision
    - torchaudio
    - --index-url https://download.pytorch.org/whl/cu124