name: medmnist
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - medmnist
    - torch
    - torchvision
    - numpy
    - pandas
    - scikit-learn
    - pillow