declare let FormulaCompiler: any;
declare let smartFormsFormulaCustomActions: any;
declare let smartFormsFormulaFixedValues: any;
declare let CodeMirror: any;
declare class RedNaoFormulaWindow {
    private FormElements;
    private Image;
    private SelectedFormElementOptions;
    private AdditionalInformation;
    private PropertyName;
    private $Dialog;
    private elementToShow;
    private codeMirror;
    private formulaText;
    private searchField;
    private autoComplete;
    private CloseCallback;
    private MethodNames;
    private FixedValues;
    constructor();
    GetCompiledData(data: FormulaData, formula: any): void;
    GetValuePropertiesFromField(fieldId: any): string;
    GetFormElementFromFormulaFieldId(field: any): sfFormElementBase<any>;
    OpenFormulaEditor(redNaoFormElements: sfFormElementBase<any>[], selectedFormElementOptions: any, propertyName: string, additionalInformation: any, image: any, closeCallBack?: () => void): void;
    CreateCustomAction(customAction: any): JQuery;
    GetHumanRedeableFormula(formula: any): any;
    GetWrappedCode(): string;
    Validate(): void;
    AddFieldToFormula(id: any): void;
    CloseFormulaEditor(redNaoFormElements: any): void;
    private Closing;
    private CreateCodeMirrorEditor;
    private GetLabel;
    private CreateFieldTag;
    private CodeMirrorChange;
    private SetCodeMirror;
    private ExecuteSearch;
    private EncodeFields;
    private DecodeFields;
    private ProcessRemoteCalls;
}
