name: random_tensor_laboratory
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cmake>=3.23
  - ffmpeg
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - pyyaml
    - matplotlib
    - scipy 
    - numpy
    - flask 
